export const INIT_CLICK = "INIT_CLICK";
export const INIT_BORDER = "INIT_BORDER";
export const INIT_BACKGROUND = "INIT_BACKGROUND";

export const CHANGE_CLICK_SIZE = "CHANGE_CLICK_SIZE";
export const CHANGE_CLICK_COLOR = "CHANGE_CLICK_COLOR";
export const CHANGE_CLICK_ENABLED = "CHANGE_CLICK_ENABLED";
export const CHANGE_CLICK_OPACITY = "CHANGE_CLICK_OPACITY";

export const CHANGE_BACKGROUND_SIZE = "CHANGE_BACKGROUND_SIZE";
export const CHANGE_BACKGROUND_COLOR = "CHANGE_BACKGROUND_COLOR";
export const CHANGE_BACKGROUND_DELAY = "CHANGE_BACKGROUND_DELAY";
export const CHANGE_BACKGROUND_OPACITY = "CHANGE_BACKGROUND_OPACITY";

export const CHANGE_BORDER_COLOR = "CHANGE_BORDER_COLOR";
export const CHANGE_BORDER_STYLE = "CHANGE_BORDER_STYLE";
export const CHANGE_BORDER_OPACITY = "CHANGE_BORDER_OPACITY";
export const CHANGE_BORDER_THICKNESS = "CHANGE_BORDER_THICKNESS";
